// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:cloud_firestore_flutter/api_key.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: ApiKeys().apiKeyAndroid,
    appId: '1:566919448334:android:65f9efbdafe5c4e7e4f95f',
    messagingSenderId: '566919448334',
    projectId: 'fir-flutter-9197a',
    storageBucket: 'fir-flutter-9197a.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: ApiKeys().apiKeyIOS,
    appId: '1:566919448334:ios:366375d73f76c92de4f95f',
    messagingSenderId: '566919448334',
    projectId: 'fir-flutter-9197a',
    storageBucket: 'fir-flutter-9197a.appspot.com',
    iosClientId: '566919448334-2aghnsnikgh90u7q35nekan18cmcbvp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudFirestoreFlutter',
  );
}
